name = "worlds-api"
main = "src/index.ts"
compatibility_date = "2026-07-18"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "worlds-api.wazoo.dev", custom_domain = true }
]

[triggers]
crons = ["0 0 * * *"]

[vars]
LIBSQL_URL = "libsql://worlds-api-prod-ethanthatonekid.aws-us-west-2.turso.io"
TURSO_ORG = "ethanthatonekid"
TURSO_GROUP = "wazoo"
MAX_DATABASES = "100"
WAZOO_ENV = "prod"

[env.qa]
name = "worlds-api-qa"
routes = [
  { pattern = "data-qa.wazoo.dev", custom_domain = true }
]

[env.qa.triggers]
crons = ["0 0 * * *"]

[env.qa.vars]
LIBSQL_URL = "libsql://worlds-api-qa-ethanthatonekid.aws-us-west-2.turso.io"
TURSO_ORG = "ethanthatonekid"
TURSO_GROUP = "wazoo"
MAX_DATABASES = "100"
WAZOO_ENV = "qa"

[observability]
enabled = true
head_sampling_rate = 1
