name = "worlds-api"
main = "src/index.ts"
compatibility_date = "2026-07-18"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "data.wazoo.dev", custom_domain = true }
]

[triggers]
crons = ["0 0 * * *"]

[[d1_databases]]
binding = "DB"
database_name = "worlds-api"
database_id = "a30635e0-c584-4447-8966-69d9b1f8a4eb"

[vars]
WAZOO_ENV = "prod"

[env.qa]
name = "worlds-api-qa"
routes = [
  { pattern = "data-qa.wazoo.dev", custom_domain = true }
]

[env.qa.triggers]
crons = ["0 0 * * *"]

[[env.qa.d1_databases]]
binding = "DB"
database_name = "worlds-api-qa"
database_id = "35823dc3-c46f-43ad-9e7b-19fe1025493f"

[env.qa.vars]
WAZOO_ENV = "qa"

[observability]
enabled = true
head_sampling_rate = 1
