// This file was generated by sql-embedder. Do not edit manually.

/**
 * metricsTable is the table for storing usage metrics
 */
export const metricsTable =
  "CREATE TABLE IF NOT EXISTS metrics (\n  id TEXT PRIMARY KEY NOT NULL,\n  service_account_id TEXT NOT NULL,\n  feature_id TEXT NOT NULL,\n  quantity INTEGER NOT NULL,\n  metadata TEXT,\n  timestamp INTEGER NOT NULL\n);";

/**
 * metricsServiceAccountIdIndex is an index on service_account_id
 */
export const metricsServiceAccountIdIndex =
  "CREATE INDEX IF NOT EXISTS idx_metrics_service_account_id ON metrics(service_account_id);";

/**
 * insertMetric inserts a new metric record
 */
export const insertMetric =
  "INSERT INTO\n  metrics (\n    id,\n    service_account_id,\n    feature_id,\n    quantity,\n    metadata,\n    timestamp\n  )\nVALUES\n  (?, ?, ?, ?, ?, ?);";

/**
 * selectLastMetric retrieves the most recent metric for a service account and feature
 */
export const selectLastMetric =
  "SELECT * FROM metrics WHERE service_account_id = ? AND feature_id = ? ORDER BY timestamp DESC LIMIT 1;";
