// This file was generated by sql-embedder. Do not edit manually.

/**
 * organizationsTable is a table where each organization owns
 * zero or more worlds.
 */
export const organizationsTable =
  "CREATE TABLE IF NOT EXISTS organizations (\n  id TEXT PRIMARY KEY NOT NULL,\n  label TEXT,\n  description TEXT,\n  plan TEXT,\n  api_key TEXT NOT NULL,\n  created_at INTEGER NOT NULL,\n  updated_at INTEGER NOT NULL,\n  deleted_at INTEGER\n);";

/**
 * organizationsApiKeyIndex is an index on api_key for secondary lookups.
 */
export const organizationsApiKeyIndex =
  "CREATE INDEX IF NOT EXISTS idx_organizations_api_key ON organizations(api_key);";

/**
 * organizationsGetMany is a query that gets organizations with pagination
 * (used in GET /v1/organizations).
 */
export const organizationsGetMany =
  "SELECT\n  *\nFROM\n  organizations\nWHERE\n  deleted_at IS NULL\nORDER BY\n  created_at DESC\nLIMIT\n  ? OFFSET ?;";

/**
 * organizationsAdd is a query that inserts a new organization
 * (used in POST /v1/organizations).
 */
export const organizationsAdd =
  "INSERT INTO\n  organizations (\n    id,\n    label,\n    description,\n    plan,\n    api_key,\n    created_at,\n    updated_at,\n    deleted_at\n  )\nVALUES\n  (?, ?, ?, ?, ?, ?, ?, ?);";

/**
 * organizationsFind is a query that finds an organization by ID
 * (used in GET /v1/organizations/:organization and auth middleware).
 */
export const organizationsFind =
  "SELECT\n  *\nFROM\n  organizations\nWHERE\n  id = ?\n  AND deleted_at IS NULL;";

/**
 * organizationsFindByApiKey is a query that finds an organization by API key
 * (used in auth middleware).
 */
export const organizationsFindByApiKey =
  "SELECT\n  *\nFROM\n  organizations\nWHERE\n  api_key = ?\n  AND deleted_at IS NULL;";

/**
 * organizationsUpdate is a query that updates organization fields
 * (used in PUT /v1/organizations/:organization).
 */
export const organizationsUpdate =
  "UPDATE\n  organizations\nSET\n  label = ?,\n  description = ?,\n  plan = ?,\n  updated_at = ?\nWHERE\n  id = ?;";

/**
 * organizationsRotateApiKey is a query that rotates an organization API key
 * (used in POST /v1/organizations/:organization/rotate).
 */
export const organizationsRotateApiKey =
  "UPDATE\n  organizations\nSET\n  api_key = ?,\n  updated_at = ?\nWHERE\n  id = ?;";

/**
 * organizationsDelete is a query that deletes an organization
 * (used in DELETE /v1/organizations/:organization).
 */
export const organizationsDelete =
  "DELETE FROM\n  organizations\nWHERE\n  id = ?;";
