// This file was generated by sql-embedder. Do not edit manually.

/**
 * worldDataTable is a singleton table to store the world's blob.
 * id=1 is enforced to ensure it's a singleton.
 */
export const worldDataTable =
  "CREATE TABLE IF NOT EXISTS world_data (\r\n  id INTEGER PRIMARY KEY CHECK (id = 1),\r\n  blob BLOB,\r\n  updated_at INTEGER NOT NULL\r\n);";

/**
 * selectWorldData fetches the singleton world data.
 */
export const selectWorldData =
  "SELECT\r\n  blob,\r\n  updated_at\r\nFROM\r\n  world_data\r\nWHERE\r\n  id = 1;";

/**
 * upsertWorldData inserts or updates the singleton world data.
 */
export const upsertWorldData =
  "INSERT INTO world_data (id, blob, updated_at)\r\nVALUES (1, ?, ?)\r\nON CONFLICT(id) DO UPDATE SET\r\n  blob = excluded.blob,\r\n  updated_at = excluded.updated_at;";
