// This file was generated by sql-embedder. Do not edit manually.

/**
 * rateLimitsTable is the table for storing rate limit bucket tokens
 */
export const rateLimitsTable =
  "CREATE TABLE IF NOT EXISTS rate_limits (\n  KEY TEXT PRIMARY KEY NOT NULL,\n  tokens REAL NOT NULL,\n  last_refill INTEGER NOT NULL\n);";

/**
 * selectRateLimitByKey retrieves a rate limit bucket by its key
 */
export const selectRateLimitByKey =
  "SELECT\n  KEY,\n  tokens,\n  last_refill\nFROM\n  rate_limits\nWHERE\n  KEY = ?;";

/**
 * insertRateLimit inserts a new rate limit bucket
 */
export const insertRateLimit =
  "INSERT INTO\n  rate_limits (KEY, tokens, last_refill)\nVALUES\n  (?, ?, ?);";

/**
 * updateRateLimit updates a rate limit bucket's tokens and last refill time
 */
export const updateRateLimit =
  "UPDATE\n  rate_limits\nSET\n  tokens = ?,\n  last_refill = ?\nWHERE\n  KEY = ?;";
