// This file was generated by sql-embedder. Do not edit manually.

/**
 * rateLimitsTable is the table for storing rate limit bucket tokens
 */
export const rateLimitsTable =
  "CREATE TABLE IF NOT EXISTS rate_limits (\r\n  key TEXT PRIMARY KEY NOT NULL,\r\n  tokens REAL NOT NULL,\r\n  last_refill INTEGER NOT NULL\r\n);";

/**
 * selectRateLimitByKey retrieves a rate limit bucket by its key
 */
export const selectRateLimitByKey =
  "SELECT\r\n  key,\r\n  tokens,\r\n  last_refill\r\nFROM\r\n  rate_limits\r\nWHERE\r\n  key = ?;";

/**
 * insertRateLimit inserts a new rate limit bucket
 */
export const insertRateLimit =
  "INSERT INTO\r\n  rate_limits (\r\n    key,\r\n    tokens,\r\n    last_refill\r\n  )\r\nVALUES\r\n  (?, ?, ?);";

/**
 * updateRateLimit updates a rate limit bucket's tokens and last refill time
 */
export const updateRateLimit =
  "UPDATE\r\n  rate_limits\r\nSET\r\n  tokens = ?,\r\n  last_refill = ?\r\nWHERE\r\n  key = ?;";
