// This file was generated by sql-embedder. Do not edit manually.

/**
 * worldsTable is a table where each world is owned by a tenant.
 * TODO: Make tenant_id nullable to support admin-created (non-tenant scoped) worlds
 */
export const worldsTable =
  "CREATE TABLE IF NOT EXISTS worlds (\n  id TEXT PRIMARY KEY NOT NULL,\n  tenant_id TEXT NOT NULL,\n  label TEXT NOT NULL,\n  description TEXT,\n  blob BLOB,\n  created_at INTEGER NOT NULL,\n  updated_at INTEGER NOT NULL,\n  deleted_at INTEGER,\n  FOREIGN KEY (tenant_id) REFERENCES tenants(id)\n);";

/**
 * worldsTenantIdIndex is an index on tenant_id for secondary lookups.
 */
export const worldsTenantIdIndex =
  "CREATE INDEX IF NOT EXISTS idx_worlds_tenant_id ON worlds(tenant_id);";

/**
 * selectWorldById is a query that finds a world by ID
 * (used in GET /v1/worlds/:world and SPARQL routes).
 */
export const selectWorldById =
  "SELECT\n  id,\n  tenant_id,\n  label,\n  description,\n  created_at,\n  updated_at,\n  deleted_at\nFROM\n  worlds\nWHERE\n  id = ?\n  AND deleted_at IS NULL;";

/**
 * selectWorldByIdWithBlob is a query that finds a world by ID and includes the blob
 * (used in binary download and SPARQL routes).
 */
export const selectWorldByIdWithBlob =
  "SELECT\n  *\nFROM\n  worlds\nWHERE\n  id = ?\n  AND deleted_at IS NULL;";

/**
 * selectWorldsByTenantId is a query that finds worlds by tenant ID with
 * pagination (used in GET /v1/worlds).
 */
export const selectWorldsByTenantId =
  "SELECT\n  id,\n  tenant_id,\n  label,\n  description,\n  created_at,\n  updated_at,\n  deleted_at\nFROM\n  worlds\nWHERE\n  tenant_id = ?\n  AND deleted_at IS NULL\nORDER BY\n  created_at DESC\nLIMIT\n  ? OFFSET ?;";

/**
 * insertWorld is a query that inserts a new world (used in POST /v1/worlds).
 */
export const insertWorld =
  "INSERT INTO\n  worlds (\n    id,\n    tenant_id,\n    label,\n    description,\n    blob,\n    created_at,\n    updated_at,\n    deleted_at\n  )\nVALUES\n  (?, ?, ?, ?, ?, ?, ?, ?);";

/**
 * updateWorld is a query that updates world fields
 * (used in PUT /v1/worlds/:world).
 */
export const updateWorld =
  "UPDATE\n  worlds\nSET\n  label = ?,\n  description = ?,\n  updated_at = ?,\n  blob = ?\nWHERE\n  id = ?;";

/**
 * deleteWorld is a query that deletes a world
 * (used in DELETE /v1/worlds/:world).
 */
export const deleteWorld = "DELETE FROM\n  worlds\nWHERE\n  id = ?;";
