// This file was generated by sql-embedder. Do not edit manually.

/**
 * tenantsTable is a table where each tenant owns
 * zero or more worlds.
 */
export const tenantsTable =
  "CREATE TABLE IF NOT EXISTS tenants (\n  id TEXT PRIMARY KEY NOT NULL,\n  label TEXT,\n  description TEXT,\n  plan TEXT,\n  api_key TEXT NOT NULL,\n  created_at INTEGER NOT NULL,\n  updated_at INTEGER NOT NULL,\n  deleted_at INTEGER\n);";

/**
 * tenantsApiKeyIndex is an index on api_key for secondary lookups.
 */
export const tenantsApiKeyIndex =
  "CREATE INDEX IF NOT EXISTS idx_tenants_api_key ON tenants(api_key);";

/**
 * tenantsGetMany is a query that gets tenants with pagination
 * (used in GET /v1/tenants).
 */
export const tenantsGetMany =
  "SELECT\n  *\nFROM\n  tenants\nWHERE\n  deleted_at IS NULL\nORDER BY\n  created_at DESC\nLIMIT\n  ? OFFSET ?;";

/**
 * tenantsAdd is a query that inserts a new tenant
 * (used in POST /v1/tenants).
 */
export const tenantsAdd =
  "INSERT INTO\n  tenants (\n    id,\n    label,\n    description,\n    plan,\n    api_key,\n    created_at,\n    updated_at,\n    deleted_at\n  )\nVALUES\n  (?, ?, ?, ?, ?, ?, ?, ?);";

/**
 * tenantsFind is a query that finds a tenant by ID
 * (used in GET /v1/tenants/:tenant and auth middleware).
 */
export const tenantsFind =
  "SELECT\n  *\nFROM\n  tenants\nWHERE\n  id = ?\n  AND deleted_at IS NULL;";

/**
 * tenantsFindByApiKey is a query that finds a tenant by API key
 * (used in auth middleware).
 */
export const tenantsFindByApiKey =
  "SELECT\n  *\nFROM\n  tenants\nWHERE\n  api_key = ?\n  AND deleted_at IS NULL;";

/**
 * tenantsUpdate is a query that updates tenant fields
 * (used in PUT /v1/tenants/:tenant).
 */
export const tenantsUpdate =
  "UPDATE\n  tenants\nSET\n  label = ?,\n  description = ?,\n  plan = ?,\n  updated_at = ?\nWHERE\n  id = ?;";

/**
 * tenantsRotateApiKey is a query that rotates a tenant API key
 * (used in POST /v1/tenants/:tenant/rotate).
 */
export const tenantsRotateApiKey =
  "UPDATE\n  tenants\nSET\n  api_key = ?,\n  updated_at = ?\nWHERE\n  id = ?;";

/**
 * tenantsDelete is a query that deletes a tenant
 * (used in DELETE /v1/tenants/:tenant).
 */
export const tenantsDelete = "DELETE FROM\n  tenants\nWHERE\n  id = ?;";
