// This file was generated by sql-embedder. Do not edit manually.

/**
 * metricsTable is the table for storing usage metrics
 */
export const metricsTable =
  "CREATE TABLE IF NOT EXISTS metrics (\r\n  id TEXT PRIMARY KEY NOT NULL,\r\n  service_account_id TEXT NOT NULL,\r\n  feature_id TEXT NOT NULL,\r\n  quantity INTEGER NOT NULL,\r\n  metadata TEXT,\r\n  timestamp INTEGER NOT NULL\r\n);";

/**
 * metricsServiceAccountIdIndex is an index on service_account_id
 */
export const metricsServiceAccountIdIndex =
  "CREATE INDEX IF NOT EXISTS idx_metrics_service_account_id ON metrics(service_account_id);";

/**
 * insertMetric inserts a new metric record
 */
export const insertMetric =
  "INSERT INTO\r\n  metrics (\r\n    id,\r\n    service_account_id,\r\n    feature_id,\r\n    quantity,\r\n    metadata,\r\n    timestamp\r\n  )\r\nVALUES\r\n  (?, ?, ?, ?, ?, ?);";

/**
 * selectLastMetric retrieves the most recent metric for a service account and feature
 */
export const selectLastMetric =
  "SELECT\r\n  *\r\nFROM\r\n  metrics\r\nWHERE\r\n  service_account_id = ?\r\n  AND feature_id = ?\r\nORDER BY\r\n  timestamp DESC\r\nLIMIT\r\n  1;";

/**
 * selectMetricsByOrganization retrieves all metrics for a given organization
 */
export const selectMetricsByOrganization =
  "SELECT\r\n  m.*\r\nFROM\r\n  metrics m\r\nJOIN\r\n  service_accounts sa ON m.service_account_id = sa.id\r\nWHERE\r\n  sa.organization_id = ?\r\nORDER BY\r\n  m.timestamp DESC;";
