// This file was generated by sql-embedder. Do not edit manually.

/**
 * serviceAccountsTable definition.
 */
export const serviceAccountsTable =
  "CREATE TABLE IF NOT EXISTS service_accounts (\r\n  id TEXT PRIMARY KEY,\r\n  organization_id TEXT NOT NULL,\r\n  api_key TEXT NOT NULL UNIQUE,\r\n  label TEXT,\r\n  description TEXT,\r\n  created_at INTEGER NOT NULL,\r\n  updated_at INTEGER NOT NULL\r\n);";

/**
 * serviceAccountsOrganizationIdIndex is an index on organization_id.
 */
export const serviceAccountsOrganizationIdIndex =
  "CREATE INDEX IF NOT EXISTS idx_service_accounts_organization_id ON service_accounts(organization_id);";

/**
 * serviceAccountsApiKeyIndex is an index on api_key.
 */
export const serviceAccountsApiKeyIndex =
  "CREATE INDEX IF NOT EXISTS idx_service_accounts_api_key ON service_accounts(api_key);";

/**
 * serviceAccountsAdd inserts a new service account.
 */
export const serviceAccountsAdd =
  "INSERT INTO\r\n  service_accounts (\r\n    id,\r\n    organization_id,\r\n    api_key,\r\n    label,\r\n    description,\r\n    created_at,\r\n    updated_at\r\n  )\r\nVALUES\r\n  (?, ?, ?, ?, ?, ?, ?);";

/**
 * serviceAccountsGetById retrieves a service account by ID.
 */
export const serviceAccountsGetById =
  "SELECT\r\n  *\r\nFROM\r\n  service_accounts\r\nWHERE\r\n  id = ?;";

/**
 * serviceAccountsGetByApiKey retrieves a service account by API key.
 */
export const serviceAccountsGetByApiKey =
  "SELECT\r\n  *\r\nFROM\r\n  service_accounts\r\nWHERE\r\n  api_key = ?;";

/**
 * serviceAccountsListByOrganizationId retrieves all service accounts for an organization.
 */
export const serviceAccountsListByOrganizationId =
  "SELECT\r\n  *\r\nFROM\r\n  service_accounts\r\nWHERE\r\n  organization_id = ?;";

/**
 * serviceAccountsUpdate updates a service account.
 */
export const serviceAccountsUpdate =
  "UPDATE\r\n  service_accounts\r\nSET\r\n  label = ?,\r\n  description = ?,\r\n  updated_at = ?\r\nWHERE\r\n  id = ?;";

/**
 * serviceAccountsRemove deletes a service account.
 */
export const serviceAccountsRemove =
  "DELETE FROM\r\n  service_accounts\r\nWHERE\r\n  id = ?;";

/**
 * serviceAccountsRotateKey updates a service account's API key.
 */
export const serviceAccountsRotateKey =
  "UPDATE\r\n  service_accounts\r\nSET\r\n  api_key = ?,\r\n  updated_at = ?\r\nWHERE\r\n  id = ?;";
