// This file was generated by sql-embedder. Do not edit manually.

/**
 * triplesTable is a table for triples with vector embeddings.
 */
export const triplesTable =
  "CREATE TABLE IF NOT EXISTS triples (\n  id TEXT PRIMARY KEY,\n  subject TEXT NOT NULL,\n  predicate TEXT NOT NULL,\n  object TEXT NOT NULL,\n  UNIQUE(subject, predicate, object)\n);";

/**
 * deleteTriples is a query that deletes a specific triple by id.
 */
export const deleteTriples = "DELETE FROM\n  triples\nWHERE\n  id = ?;";

/**
 * upsertTriples is a query that inserts or replaces a triple with
 * embedding.
 */
export const upsertTriples =
  "INSERT\n  OR REPLACE INTO triples (\n    id,\n    subject,\n    predicate,\n    object\n  )\nVALUES\n  (?, ?, ?, ?);";
