// This file was generated by sql-embedder. Do not edit manually.

/**
 * tokenBucketsTable implements the Token Bucket algorithm for rate limiting.
 * Reference: https://en.wikipedia.org/wiki/Token_bucket
 */
export const tokenBucketsTable =
  "CREATE TABLE IF NOT EXISTS token_buckets (\n  id TEXT PRIMARY KEY NOT NULL,\n  organization_id TEXT NOT NULL,\n  KEY TEXT NOT NULL,  -- Composite key: worldId:resourceType\n  tokens REAL NOT NULL,\n  last_refill_at INTEGER NOT NULL,\n  FOREIGN KEY (organization_id) REFERENCES organizations(id)\n);";

/**
 * tokenBucketsOrganizationIdIndex is an index on organization_id for efficient lookups
 * by organization.
 */
export const tokenBucketsOrganizationIdIndex =
  "CREATE INDEX IF NOT EXISTS idx_token_buckets_organization_id ON token_buckets(\n  organization_id\n);";

/**
 * tokenBucketsFind is a query that finds a token bucket by key
 * (used in rate limiter consume operation).
 */
export const tokenBucketsFind =
  "SELECT\n  *\nFROM\n  token_buckets\nWHERE\n  KEY = ?;";

/**
 * tokenBucketsUpsert is a query that inserts or updates a token bucket
 * (used in rate limiter atomic operations).
 */
export const tokenBucketsUpsert =
  "INSERT\n  OR REPLACE INTO token_buckets (\n    id,\n    organization_id,\n    KEY,\n    tokens,\n    last_refill_at\n  )\nVALUES\n  (?, ?, ?, ?, ?);";

/**
 * tokenBucketsDeleteByOrganization is a query that deletes all token buckets for
 * an organization (cleanup when organization is deleted).
 */
export const tokenBucketsDeleteByOrganization =
  "DELETE FROM\n  token_buckets\nWHERE\n  organization_id = ?;";

/**
 * tokenBucketsCleanupOld is a query that deletes token buckets that haven't
 * been used in a while (maintenance query).
 */
export const tokenBucketsCleanupOld =
  "DELETE FROM\n  token_buckets\nWHERE\n  last_refill_at < ?;";
