// This file was generated by sql-embedder. Do not edit manually.

/**
 * tokenBucketsTable implements the Token Bucket algorithm for rate limiting.
 * Reference: https://en.wikipedia.org/wiki/Token_bucket
 */
export const tokenBucketsTable =
  "CREATE TABLE IF NOT EXISTS token_buckets (\n  id TEXT PRIMARY KEY NOT NULL,\n  tenant_id TEXT NOT NULL,\n  KEY TEXT NOT NULL,  -- Composite key: worldId:resourceType\n  tokens REAL NOT NULL,\n  last_refill_at INTEGER NOT NULL,\n  FOREIGN KEY (tenant_id) REFERENCES tenants(id)\n);";

/**
 * tokenBucketsTenantIdIndex is an index on tenant_id for efficient lookups
 * by tenant.
 */
export const tokenBucketsTenantIdIndex =
  "CREATE INDEX IF NOT EXISTS idx_token_buckets_tenant_id ON token_buckets(tenant_id);";

/**
 * tokenBucketsFind is a query that finds a token bucket by key
 * (used in rate limiter consume operation).
 */
export const tokenBucketsFind =
  "SELECT\n  *\nFROM\n  token_buckets\nWHERE\n  KEY = ?;";

/**
 * tokenBucketsUpsert is a query that inserts or updates a token bucket
 * (used in rate limiter atomic operations).
 */
export const tokenBucketsUpsert =
  "INSERT\n  OR REPLACE INTO token_buckets (id, tenant_id, KEY, tokens, last_refill_at)\nVALUES\n  (?, ?, ?, ?, ?);";

/**
 * tokenBucketsDeleteByTenant is a query that deletes all token buckets for
 * a tenant (cleanup when tenant is deleted).
 */
export const tokenBucketsDeleteByTenant =
  "DELETE FROM\n  token_buckets\nWHERE\n  tenant_id = ?;";

/**
 * tokenBucketsCleanupOld is a query that deletes token buckets that haven't
 * been used in a while (maintenance query).
 */
export const tokenBucketsCleanupOld =
  "DELETE FROM\n  token_buckets\nWHERE\n  last_refill_at < ?;";
