// This file was generated by sql-embedder. Do not edit manually.

/**
 * blobsTable is a singleton table to store the world's blob.
 * id=1 is enforced to ensure it's a singleton.
 */
export const blobsTable =
  "CREATE TABLE IF NOT EXISTS blobs (\n  id INTEGER PRIMARY KEY CHECK (id = 1),\n  blob BLOB,\n  updated_at INTEGER NOT NULL\n);";

/**
 * selectBlob fetches the singleton world blob.
 */
export const selectBlob =
  "SELECT\n  blob,\n  updated_at\nFROM\n  blobs\nWHERE\n  id = 1;";

/**
 * upsertBlob inserts or updates the singleton world blob.
 */
export const upsertBlob =
  "INSERT INTO\n  blobs (id, blob, updated_at)\nVALUES\n  (1, ?, ?) ON CONFLICT(id) DO\nUPDATE\nSET\n  blob = excluded.blob,\n  updated_at = excluded.updated_at;";
