// This file was generated by sql-embedder. Do not edit manually.

/**
 * invitesTable is a table where each invite allows a user to be promoted to the free plan.
 * An invite allows a user with a nullish plan to be promoted to the free plan
 * upon redemption. Once redeemed, the invite cannot be used again.
 */
export const invitesTable =
  "CREATE TABLE IF NOT EXISTS invites (\n  code TEXT PRIMARY KEY NOT NULL,\n  created_at INTEGER NOT NULL,\n  redeemed_by TEXT,\n  redeemed_at INTEGER\n);";

/**
 * invitesRedeemedByIndex is an index on redeemed_by for secondary lookups
 * (was a kvdex secondary index).
 */
export const invitesRedeemedByIndex =
  "CREATE INDEX IF NOT EXISTS idx_invites_redeemed_by ON invites(redeemed_by);";

/**
 * invitesGetMany is a query that gets invites with pagination
 * (used in GET /v1/invites).
 */
export const invitesGetMany =
  "SELECT\n  *\nFROM\n  invites\nORDER BY\n  created_at DESC\nLIMIT\n  ? OFFSET ?;";

/**
 * invitesAdd is a query that inserts a new invite
 * (used in POST /v1/invites).
 */
export const invitesAdd =
  "INSERT INTO\n  invites (code, created_at, redeemed_by, redeemed_at)\nVALUES\n  (?, ?, ?, ?);";

/**
 * invitesFind is a query that finds an invite by code
 * (used in GET /v1/invites/:code and POST /v1/invites/:code/redeem).
 */
export const invitesFind = "SELECT\n  *\nFROM\n  invites\nWHERE\n  code = ?;";

/**
 * invitesUpdate is a query that updates an invite (mark as redeemed in
 * POST /v1/invites/:code/redeem).
 */
export const invitesUpdate =
  "UPDATE\n  invites\nSET\n  redeemed_by = ?,\n  redeemed_at = ?\nWHERE\n  code = ?;";

/**
 * invitesDelete is a query that deletes an invite
 * (used in DELETE /v1/invites/:code).
 */
export const invitesDelete = "DELETE FROM\n  invites\nWHERE\n  code = ?;";
