// This file was generated by sql-embedder. Do not edit manually.

/**
 * organizationsTable is a table where each organization owns
 * zero or more worlds.
 */
export const organizationsTable =
  "CREATE TABLE IF NOT EXISTS organizations (\n  id TEXT PRIMARY KEY NOT NULL,\n  label TEXT,\n  description TEXT,\n  plan TEXT,\n  created_at INTEGER NOT NULL,\n  updated_at INTEGER NOT NULL,\n  deleted_at INTEGER\n);";

/**
 * selectOrganizations is a query that gets organizations with pagination
 * (used in GET /v1/organizations).
 */
export const selectOrganizations =
  "SELECT\n  *\nFROM\n  organizations\nWHERE\n  deleted_at IS NULL\nORDER BY\n  created_at DESC\nLIMIT\n  ? OFFSET ?;";

/**
 * insertOrganization is a query that inserts a new organization
 * (used in POST /v1/organizations).
 */
export const insertOrganization =
  "INSERT INTO\n  organizations (\n    id,\n    label,\n    description,\n    plan,\n    created_at,\n    updated_at,\n    deleted_at\n  )\nVALUES\n  (?, ?, ?, ?, ?, ?, ?);";

/**
 * selectOrganizationById is a query that finds an organization by ID
 * (used in GET /v1/organizations/:organization and auth middleware).
 */
export const selectOrganizationById =
  "SELECT\n  *\nFROM\n  organizations\nWHERE\n  id = ?\n  AND deleted_at IS NULL;";

/**
 * updateOrganization is a query that updates organization fields
 * (used in PUT /v1/organizations/:organization).
 */
export const updateOrganization =
  "UPDATE\n  organizations\nSET\n  label = ?,\n  description = ?,\n  plan = ?,\n  updated_at = ?\nWHERE\n  id = ?;";

/**
 * deleteOrganization is a query that deletes an organization
 * (used in DELETE /v1/organizations/:organization).
 */
export const deleteOrganization =
  "DELETE FROM\n  organizations\nWHERE\n  id = ?;";
