// This file was generated by sql-embedder. Do not edit manually.

/**
 * factsTable is a table for facts with vector embeddings.
 */
export const factsTable =
  "CREATE TABLE IF NOT EXISTS facts (\n  id TEXT PRIMARY KEY,\n  item_id TEXT NOT NULL,\n  property TEXT NOT NULL,\n  value TEXT NOT NULL,\n  vector F32_BLOB(1536),\n  UNIQUE(item_id, property, value)\n);";

/**
 * factsItemIdIndex is an index on item_id for efficient filtering.
 */
export const factsItemIdIndex =
  "CREATE INDEX IF NOT EXISTS idx_facts_item_id ON facts(item_id);";

/**
 * factsPropertyIndex is an index on property for efficient filtering.
 */
export const factsPropertyIndex =
  "CREATE INDEX IF NOT EXISTS idx_facts_property ON facts(property);";

/**
 * factsVectorIndex is a vector index for similarity search.
 */
export const factsVectorIndex =
  "CREATE INDEX IF NOT EXISTS idx_facts_vector ON facts(libsql_vector_idx(vector));";

/**
 * factsFtsTable is an FTS5 virtual table for full-text search.
 */
export const factsFtsTable =
  "CREATE VIRTUAL TABLE IF NOT EXISTS facts_fts USING fts5(\n  value,\n  content = 'facts',\n  content_rowid = 'rowid'\n);";

/**
 * factsFtsInsertTrigger is a trigger to sync FTS after insert.
 */
export const factsFtsInsertTrigger =
  "CREATE TRIGGER IF NOT EXISTS facts_ai\nAFTER\nINSERT\n  ON facts\nBEGIN\nINSERT INTO\n  facts_fts(rowid, value)\nVALUES\n  (new.rowid, new.value);\n\nEND;";

/**
 * factsFtsDeleteTrigger is a trigger to sync FTS after delete.
 */
export const factsFtsDeleteTrigger =
  "CREATE TRIGGER IF NOT EXISTS facts_ad\nAFTER\n  DELETE ON facts\nBEGIN\nINSERT INTO\n  facts_fts(facts_fts, rowid, value)\nVALUES\n  ('delete', old.rowid, old.value);\n\nEND;";

/**
 * factsFtsUpdateTrigger is a trigger to sync FTS after update.
 */
export const factsFtsUpdateTrigger =
  "CREATE TRIGGER IF NOT EXISTS facts_au\nAFTER\nUPDATE\n  ON facts\nBEGIN\nINSERT INTO\n  facts_fts(facts_fts, rowid, value)\nVALUES\n  ('delete', old.rowid, old.value);\n\nINSERT INTO\n  facts_fts(rowid, value)\nVALUES\n  (new.rowid, new.value);\n\nEND;";

/**
 * deleteFacts is a query that deletes a specific fact by id.
 */
export const deleteFacts = "DELETE FROM\n  facts\nWHERE\n  id = ?;";

/**
 * upsertFacts is a query that inserts or replaces a fact with
 * embedding.
 */
export const upsertFacts =
  "INSERT\n  OR REPLACE INTO facts (\n    id,\n    item_id,\n    property,\n    value,\n    vector\n  )\nVALUES\n  (?, ?, ?, ?, vector32(?));";

/**
 * searchFacts is a query that performs hybrid search using RRF
 * (Reciprocal Rank Fusion) combining FTS and vector search.
 * Supports optional filtering by item_id and property.
 */
export const searchFacts =
  "WITH vec_matches AS (\n  SELECT\n    id AS rowid,\n    row_number() OVER (PARTITION BY NULL) AS rank_number\n  FROM\n    vector_top_k('idx_facts_vector', vector32(?), ?)\n),\nfts_matches AS (\n  SELECT\n    rowid,\n    row_number() OVER (\n      ORDER BY\n        rank\n    ) AS rank_number,\n    rank AS score\n  FROM\n    facts_fts\n  WHERE\n    facts_fts MATCH ?\n  LIMIT\n    ?\n), final AS (\n  SELECT\n    facts.item_id,\n    facts.property,\n    facts.value,\n    vec_matches.rank_number AS vec_rank,\n    fts_matches.rank_number AS fts_rank,\n    (\n      COALESCE(1.0 / (60 + fts_matches.rank_number), 0.0) * 1.0 + COALESCE(1.0 / (60 + vec_matches.rank_number), 0.0) * 1.0\n    ) AS combined_rank\n  FROM\n    fts_matches\n    FULL OUTER JOIN vec_matches ON vec_matches.rowid = fts_matches.rowid\n    JOIN facts ON facts.rowid = COALESCE(fts_matches.rowid, vec_matches.rowid)\n  WHERE\n    (\n      ? IS NULL\n      OR facts.item_id IN (\n        SELECT\n          value\n        FROM\n          json_each(?)\n      )\n    )\n    AND (\n      ? IS NULL\n      OR facts.property IN (\n        SELECT\n          value\n        FROM\n          json_each(?)\n      )\n    )\n  ORDER BY\n    combined_rank DESC\n  LIMIT\n    ?\n)\nSELECT\n  *\nFROM\n  final;";
