// This file was generated by sql-embedder. Do not edit manually.

/**
 * worldsTable is a table where each world is owned by an organization.
 * TODO: Make organization_id nullable to support admin-created (non-org scoped) worlds
 */
export const worldsTable =
  "CREATE TABLE IF NOT EXISTS worlds (\n  id TEXT PRIMARY KEY NOT NULL,\n  organization_id TEXT NOT NULL,\n  label TEXT NOT NULL,\n  description TEXT,\n  db_hostname TEXT,\n  db_token TEXT,\n  created_at INTEGER NOT NULL,\n  updated_at INTEGER NOT NULL,\n  deleted_at INTEGER,\n  FOREIGN KEY (organization_id) REFERENCES organizations(id)\n);";

/**
 * worldsOrganizationIdIndex is an index on organization_id for secondary lookups.
 */
export const worldsOrganizationIdIndex =
  "CREATE INDEX IF NOT EXISTS idx_worlds_organization_id ON worlds(organization_id);";

/**
 * selectWorldById is a query that finds a world by ID
 * (used in GET /v1/worlds/:world and SPARQL routes).
 */
export const selectWorldById =
  "SELECT\n  id,\n  organization_id,\n  label,\n  description,\n  db_hostname,\n  db_token,\n  created_at,\n  updated_at,\n  deleted_at\nFROM\n  worlds\nWHERE\n  id = ?\n  AND deleted_at IS NULL;";

/**
 * selectWorldByIdWithBlob (deprecated, now same as selectWorldById)
 */
export const selectWorldByIdWithBlob =
  "SELECT\n  id,\n  organization_id,\n  label,\n  description,\n  db_hostname,\n  db_token,\n  created_at,\n  updated_at,\n  deleted_at\nFROM\n  worlds\nWHERE\n  id = ?\n  AND deleted_at IS NULL;";

/**
 * selectWorldsByOrganizationId is a query that finds worlds by organization ID with
 * pagination (used in GET /v1/worlds).
 */
export const selectWorldsByOrganizationId =
  "SELECT\n  id,\n  organization_id,\n  label,\n  description,\n  db_hostname,\n  db_token,\n  created_at,\n  updated_at,\n  deleted_at\nFROM\n  worlds\nWHERE\n  organization_id = ?\n  AND deleted_at IS NULL\nORDER BY\n  created_at DESC\nLIMIT\n  ? OFFSET ?;";

/**
 * insertWorld is a query that inserts a new world (used in POST /v1/worlds).
 */
export const insertWorld =
  "INSERT INTO\n  worlds (\n    id,\n    organization_id,\n    label,\n    description,\n    db_hostname,\n    db_token,\n    created_at,\n    updated_at,\n    deleted_at\n  )\nVALUES\n  (?, ?, ?, ?, ?, ?, ?, ?, ?);";

/**
 * updateWorld is a query that updates world fields
 * (used in PUT /v1/worlds/:world).
 */
export const updateWorld =
  "UPDATE\n  worlds\nSET\n  label = ?,\n  description = ?,\n  updated_at = ?,\n  db_hostname = ?,\n  db_token = ?,\n  deleted_at = ?\nWHERE\n  id = ?;";

/**
 * deleteWorld is a query that deletes a world
 * (used in DELETE /v1/worlds/:world).
 */
export const deleteWorld = "DELETE FROM\n  worlds\nWHERE\n  id = ?;";
