// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

/**
 * Request to create a new world.
 */
export type CreateWorldRequest = {
  /**
   * Namespace the world belongs to.
   */
  namespace: string;
  /**
   * Client-chosen unique identifier for the world.
   */
  id: string;
  /**
   * Human-friendly display name.
   */
  displayName?: string;
  /**
   * Optional description of the world.
   */
  description?: string;
};

/**
 * Response after successfully creating a world.
 */
export type CreateWorldResponse = {
  world: World;
};

/**
 * Request to get a world by name.
 */
export type GetWorldRequest = {
  /**
   * The canonical resource name.
   */
  name: string;
};

export type GetWorldResponse = {
  world?: World;
};

export type CreateWorldRpcError = {
  action: "createWorld";
  error: RpcErrorObject;
};

export type CreateWorldRpcRequest = {
  action: "createWorld";
  request: CreateWorldRequest;
};

export type CreateWorldRpcResponse = {
  action: "createWorld";
  response: CreateWorldResponse;
};

export type GetWorldRpcError = {
  action: "getWorld";
  error: RpcErrorObject;
};

export type GetWorldRpcRequest = {
  action: "getWorld";
  request: GetWorldRequest;
};

export type GetWorldRpcResponse = {
  action: "getWorld";
  response: GetWorldResponse;
};

/**
 * Error payload for RPC failures.
 */
export type RpcErrorObject = {
  code?: string;
  message?: string;
  /**
   * Optional structured error details.
   */
  details?: {
    [key: string]: unknown;
  };
  [key: string]: unknown;
};

export type WorldsError =
  | ({
    action: "getWorld";
  } & GetWorldRpcError)
  | ({
    action: "createWorld";
  } & CreateWorldRpcError);

export type WorldsRequest =
  | ({
    action: "getWorld";
  } & GetWorldRpcRequest)
  | ({
    action: "createWorld";
  } & CreateWorldRpcRequest);

export type WorldsResponse =
  | ({
    action: "getWorld";
  } & GetWorldRpcResponse)
  | ({
    action: "createWorld";
  } & CreateWorldRpcResponse);

/**
 * Metadata for a single world.
 */
export type World = {
  /**
   * The canonical resource name.
   */
  name?: string;
  /**
   * The unique identifier for the world.
   */
  id?: string;
  /**
   * The namespace for the world.
   */
  namespace?: string;
  /**
   * The display name for the world.
   */
  displayName?: string;
  /**
   * The description for the world.
   */
  description?: string;
  /**
   * The creation time for the world.
   */
  createTime?: number;
};

export type WorldsRpcData = {
  body: WorldsRequest;
  path?: never;
  query?: never;
  url: "/rpc";
};

export type WorldsRpcErrors = {
  /**
   * RPC error
   */
  400: WorldsError;
};

export type WorldsRpcError = WorldsRpcErrors[keyof WorldsRpcErrors];

export type WorldsRpcResponses = {
  /**
   * Success
   */
  200: WorldsResponse;
};

export type WorldsRpcResponse = WorldsRpcResponses[keyof WorldsRpcResponses];
