// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * Metadata for a single world.
 */
export type World = {
    /**
     * The canonical resource name.
     */
    name?: string;
    /**
     * The unique identifier for the world.
     */
    id?: string;
    /**
     * The namespace for the world.
     */
    namespace?: string;
    /**
     * The display name for the world.
     */
    displayName?: string;
    /**
     * The description for the world.
     */
    description?: string;
    /**
     * The creation time for the world.
     */
    createTime?: number;
};
