// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

/**
 * Metadata for a single world.
 */
export const zWorld = z.object({
    name: z.string().optional(),
    id: z.string().optional(),
    namespace: z.string().optional(),
    displayName: z.string().optional(),
    description: z.string().optional(),
    createTime: z.number().optional()
});
