// This file was generated by sql-embedder. Do not edit manually.

/**
 * logsTable is the table definition for system logs.
 */
export const logsTable =
  "CREATE TABLE IF NOT EXISTS LOGS (\r\n  id TEXT PRIMARY KEY,\r\n  world_id TEXT,\r\n  timestamp INTEGER NOT NULL,\r\n  LEVEL TEXT NOT NULL,\r\n  message TEXT NOT NULL,\r\n  metadata TEXT\r\n);";

/**
 * logsWorldIdIndex is an index on world_id for faster filtering.
 */
export const logsWorldIdIndex =
  "CREATE INDEX IF NOT EXISTS idx_logs_world_id ON LOGS(world_id);";

/**
 * logsTimestampIndex is an index on timestamp for time-based graphical queries and cleanup.
 */
export const logsTimestampIndex =
  "CREATE INDEX IF NOT EXISTS idx_logs_timestamp ON LOGS(timestamp);";

/**
 * logsAdd inserts a new log entry.
 */
export const logsAdd =
  "INSERT INTO\r\n  LOGS (\r\n    id,\r\n    world_id,\r\n    timestamp,\r\n    LEVEL,\r\n    message,\r\n    metadata\r\n  )\r\nVALUES\r\n  (?, ?, ?, ?, ?, ?);";

/**
 * logsList retrieves logs for a specific world, with optional level filtering, ordered by time descending.
 */
export const logsList =
  "SELECT\r\n  *\r\nFROM\r\n  LOGS\r\nWHERE\r\n  world_id = ?\r\n  AND (? IS NULL OR LEVEL = ?)\r\nORDER BY\r\n  timestamp DESC\r\nLIMIT\r\n  ?\r\nOFFSET\r\n  ?;";

/**
 * logsListSince retrieves logs after a timestamp for streaming.
 */
export const logsListSince =
  "SELECT\r\n  *\r\nFROM\r\n  LOGS\r\nWHERE\r\n  timestamp > ?\r\nORDER BY\r\n  timestamp ASC\r\nLIMIT\r\n  ?;";

/**
 * logsDeleteExpired deletes logs older than a specific timestamp (TTL).
 */
export const logsDeleteExpired =
  "DELETE FROM\r\n  LOGS\r\nWHERE\r\n  timestamp < ?;";
