// This file was generated by sql-embedder. Do not edit manually.

/**
 * serviceAccountsTable definition.
 */
export const serviceAccountsTable =
  "CREATE TABLE IF NOT EXISTS service_accounts (\n  id TEXT PRIMARY KEY,\n  organization_id TEXT NOT NULL,\n  api_key TEXT NOT NULL UNIQUE,\n  label TEXT,\n  description TEXT,\n  created_at INTEGER NOT NULL,\n  updated_at INTEGER NOT NULL\n);";

/**
 * serviceAccountsOrganizationIdIndex is an index on organization_id.
 */
export const serviceAccountsOrganizationIdIndex =
  "CREATE INDEX IF NOT EXISTS idx_service_accounts_organization_id ON service_accounts(organization_id);";

/**
 * serviceAccountsApiKeyIndex is an index on api_key.
 */
export const serviceAccountsApiKeyIndex =
  "CREATE INDEX IF NOT EXISTS idx_service_accounts_api_key ON service_accounts(api_key);";

/**
 * serviceAccountsAdd inserts a new service account.
 */
export const serviceAccountsAdd =
  "INSERT INTO\n  service_accounts (\n    id,\n    organization_id,\n    api_key,\n    label,\n    description,\n    created_at,\n    updated_at\n  )\nVALUES\n  (?, ?, ?, ?, ?, ?, ?);";

/**
 * serviceAccountsGetById retrieves a service account by ID.
 */
export const serviceAccountsGetById =
  "SELECT\n  *\nFROM\n  service_accounts\nWHERE\n  id = ?;";

/**
 * serviceAccountsGetByApiKey retrieves a service account by API key.
 */
export const serviceAccountsGetByApiKey =
  "SELECT\n  *\nFROM\n  service_accounts\nWHERE\n  api_key = ?;";

/**
 * serviceAccountsListByOrganizationId retrieves all service accounts for an organization.
 */
export const serviceAccountsListByOrganizationId =
  "SELECT\n  *\nFROM\n  service_accounts\nWHERE\n  organization_id = ?;";

/**
 * serviceAccountsUpdate updates a service account.
 */
export const serviceAccountsUpdate =
  "UPDATE\n  service_accounts\nSET\n  label = ?,\n  description = ?,\n  updated_at = ?\nWHERE\n  id = ?;";

/**
 * serviceAccountsRemove deletes a service account.
 */
export const serviceAccountsRemove =
  "DELETE FROM\n  service_accounts\nWHERE\n  id = ?;";
